[FEATURE] Add new activity type Vlab activity (#2940)
* duplication of multi-input activity as vlab

* Add force to npm install to override peer dependency issue.

* Add a Vlab to the default stem

* Fix bug causing extra input to be added.  See bugfix #2590, https://github.com/Simon-Initiative/oli-torus/pull/2590.

* Add vlab to static and enable route.

* Query vlab for selected vessel volume on inout update and write to console.

* Force input value to vlab selectedFlask.volume onChange of input

* Update model to add VlabInput type.  Begin to migrate over UI sections from multiInput.

* update gitIgnore to ignore assets/static/vlab and packagelock.json (though I am not sure that is right).

* Add logic from new input type 'VlabInput'.  In progress.  Shows up in input ref menu, doesn't render.

* Part of previous commit.

* Add new input type VlabInput.

* Added listener for vlab change event.

* Vlab activity now works for volume parameter only.

* Parameterize vlab parameter (e.g. temp, volume) to test for.

* Add type for VlabParameter, display selected value on Question tab, ultimately will be set from Question tab. Also add style for vlab-holder.

* Simplified structure and better styling of VlabInput

* Build out vlab parameter selector.  Add new utility function to set Vlab species.  Add XML parsing for Vlab species queries.

* Add support for author to specify assignment path.  Also fixed VlabParameterSelector to use author provided value (not '1').

* VlabConfigTab

* Add molarity to vlab parameter list.  Use placeholder image instead of live vlab in author view.

* Add support for pH and concentration (g/L).

* Typo

* Catch up to master features since branch creation (March 28, 2022).
Edit devmode.sh to use Yarn instead of NPM for build.

* Add editors and hooks to put Vlab config JSON onto model.

* Add support for ingest of configuration via JSON objects, editable in Torus.

* Move JSON editors to config tab.

* Also author to choose built-in assignment file from a list or to supply JSON.

* Add selector for pre-built activities.

* Clean-up weeding.

* Misc clean up.

* Add static vlab build (Aug 18, 2022) to repository

* Update CHANGELOG

* Add missing values to VlabSchema.  Type clean up in VlabDelivery.

* Fix typing errors, passes jest test suite.

* Added support for multiple Vlabs on a page via unique identifier model.stem.id

* Added VlabInputDelivery to writer/context.ts to resolve type check fail.

FAIL test/multi_input/multi_input_authoring_test.tsx
  ● Test suite failed to run

    src/data/content/writers/html.tsx:394:12 - error TS2678: Type '"vlabvalue"' is not comparable to type '"text" | "math" | "dropdown" | "numeric"'.

    394       case 'vlabvalue':
                   ~~~~~~~~~~~

Might not be the best solution?  Should there be one ActivityInputDelivery that includes all input types?

* prevent vlab appearing in multiinput

* Cast input to VlabValue, not VlabInput.

* Add vlab.png for author view to repo.

* add math to resolve typing issue

* remove console.log

Co-authored-by: Darren Siegel <siegel.darren@gmail.com>